// AUTO-GENERATED by _work/pdfium/render.mjs — the number of designed magazine
// page images in public/magazine/pages (01.webp .. NN.webp). Kept as a bundled
// constant (not a runtime fs read) because public/ is not reliably present in
// the Vercel serverless filesystem.
export const MAGAZINE_PAGES = 36;
